import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { requireAuth } from "@/lib/supabase/middleware";
import { logActivity } from "@/lib/logActivity";

const transferItemSchema = z.object({
  product_id: z.string().uuid(),
  qty: z.number().int().min(1),
  sort_order: z.number().int().min(0).default(0),
});

const createTransferSchema = z.object({
  from_storage_id: z.string().uuid(),
  to_storage_id: z.string().uuid(),
  notes: z.string().optional().nullable(),
  items: z.array(transferItemSchema).min(1),
});

export async function GET(request: NextRequest) {
  const { error } = await requireAuth(request);
  if (error) return error;

  const storageId = request.nextUrl.searchParams.get("storage_id");

  const supabase = createServerSupabaseClient();

  let query = supabase
    .from("storage_transfers")
    .select(
      `
      id, transfer_number, from_storage_id, to_storage_id, notes, created_by, created_at,
      from_storage:storages!storage_transfers_from_storage_id_fkey(id, name_en, name_ar, icon),
      to_storage:storages!storage_transfers_to_storage_id_fkey(id, name_en, name_ar, icon),
      creator:profiles!storage_transfers_created_by_fkey(id, full_name),
      storage_transfer_items(
        id, product_id, qty, sort_order,
        product:products(id, sku, name_en, name_ar, category, unit_price)
      )
    `
    )
    .order("created_at", { ascending: false });

  if (storageId) {
    query = query.or(`from_storage_id.eq.${storageId},to_storage_id.eq.${storageId}`);
  }

  const { data, error: dbError } = await query;

  if (dbError) return NextResponse.json({ error: dbError.message }, { status: 500 });

  return NextResponse.json(data ?? []);
}

export async function POST(request: NextRequest) {
  const { user, error } = await requireAuth(request);
  if (error) return error;

  const body = await request.json().catch(() => null);
  const parsed = createTransferSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json({ error: parsed.error.issues.map((i) => i.message).join(", ") }, { status: 400 });
  }

  const { from_storage_id, to_storage_id, notes, items } = parsed.data;

  if (from_storage_id === to_storage_id) {
    return NextResponse.json({ error: "Source and destination storages must be different." }, { status: 400 });
  }

  const supabase = createServerSupabaseClient();

  // Verify sufficient qty in source for each product
  for (const item of items) {
    const { data: ps } = await supabase
      .from("product_storages")
      .select("qty")
      .eq("product_id", item.product_id)
      .eq("storage_id", from_storage_id)
      .single();

    if (!ps || ps.qty < item.qty) {
      const { data: prod } = await supabase
        .from("products")
        .select("name_en")
        .eq("id", item.product_id)
        .single();
      return NextResponse.json(
        { error: `Insufficient qty for "${prod?.name_en ?? item.product_id}" in source storage.` },
        { status: 422 }
      );
    }
  }

  // Insert transfer header (transfer_number auto-generated by trigger)
  const { data: transfer, error: transferError } = await supabase
    .from("storage_transfers")
    .insert({ from_storage_id, to_storage_id, notes, created_by: user!.id })
    .select()
    .single();

  if (transferError) return NextResponse.json({ error: transferError.message }, { status: 500 });

  // Insert transfer items
  const { error: itemsError } = await supabase.from("storage_transfer_items").insert(
    items.map((item) => ({
      transfer_id: transfer.id,
      product_id: item.product_id,
      qty: item.qty,
      sort_order: item.sort_order,
    }))
  );

  if (itemsError) return NextResponse.json({ error: itemsError.message }, { status: 500 });

  // Update product_storages: deduct from source, upsert into destination
  for (const item of items) {
    // Deduct from source
    const { data: src } = await supabase
      .from("product_storages")
      .select("qty")
      .eq("product_id", item.product_id)
      .eq("storage_id", from_storage_id)
      .single();

    if (src) {
      const newQty = src.qty - item.qty;
      if (newQty <= 0) {
        await supabase
          .from("product_storages")
          .delete()
          .eq("product_id", item.product_id)
          .eq("storage_id", from_storage_id);
      } else {
        await supabase
          .from("product_storages")
          .update({ qty: newQty })
          .eq("product_id", item.product_id)
          .eq("storage_id", from_storage_id);
      }
    }

    // Upsert into destination
    const { data: dest } = await supabase
      .from("product_storages")
      .select("id, qty")
      .eq("product_id", item.product_id)
      .eq("storage_id", to_storage_id)
      .maybeSingle();

    if (dest) {
      await supabase
        .from("product_storages")
        .update({ qty: dest.qty + item.qty })
        .eq("id", dest.id);
    } else {
      await supabase
        .from("product_storages")
        .insert({ product_id: item.product_id, storage_id: to_storage_id, qty: item.qty });
    }
  }

  await logActivity({
    supabase,
    userId: user!.id,
    entityType: "transfer",
    entityId: transfer.id,
    action: "created",
    summary: `Created transfer ${transfer.transfer_number}: ${items.length} item(s) moved`,
  });

  return NextResponse.json(transfer, { status: 201 });
}
