import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { requireAuth } from "@/lib/supabase/middleware";
import { logActivity } from "@/lib/logActivity";

const restockItemSchema = z.object({
  product_id: z.string().uuid(),
  qty_before: z.number().int().min(0),
  qty_after: z.number().int().min(0),
  sort_order: z.number().int().min(0).default(0),
});

const createRestockSchema = z.object({
  notes: z.string().optional().nullable(),
  items: z.array(restockItemSchema).min(1),
});

export async function GET(request: NextRequest) {
  const { error } = await requireAuth(request);
  if (error) return error;

  const supabase = createServerSupabaseClient();

  const { data, error: dbError } = await supabase
    .from("restock_reports")
    .select(
      `
      id, report_number, notes, created_by, created_at,
      creator:profiles!restock_reports_created_by_fkey(id, full_name),
      restock_report_items(
        id, report_id, product_id, qty_before, qty_after, sort_order,
        product:products(id, sku, name_en, name_ar, category, unit_price)
      )
    `
    )
    .order("created_at", { ascending: false });

  if (dbError) return NextResponse.json({ error: dbError.message }, { status: 500 });

  return NextResponse.json(data ?? []);
}

export async function POST(request: NextRequest) {
  const { user, error } = await requireAuth(request);
  if (error) return error;

  const body = await request.json().catch(() => null);
  const parsed = createRestockSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json(
      { error: parsed.error.issues.map((i) => i.message).join(", ") },
      { status: 400 }
    );
  }

  const { notes, items } = parsed.data;
  const supabase = createServerSupabaseClient();

  // Insert report header — report_number auto-generated by trigger
  const { data: report, error: reportError } = await supabase
    .from("restock_reports")
    .insert({ notes: notes ?? null, created_by: user!.id, report_number: "" })
    .select()
    .single();

  if (reportError || !report) {
    return NextResponse.json({ error: reportError?.message ?? "Failed to create report" }, { status: 500 });
  }

  // Insert items
  const { error: itemsError } = await supabase.from("restock_report_items").insert(
    items.map((item) => ({
      report_id: report.id,
      product_id: item.product_id,
      qty_before: item.qty_before,
      qty_after: item.qty_after,
      sort_order: item.sort_order,
    }))
  );

  if (itemsError) {
    return NextResponse.json({ error: itemsError.message }, { status: 500 });
  }

  // Update stock_qty for each product
  for (const item of items) {
    await supabase
      .from("products")
      .update({ stock_qty: item.qty_after })
      .eq("id", item.product_id);
  }

  await logActivity({
    supabase,
    userId: user!.id,
    entityType: "restock_report",
    entityId: report.id,
    action: "created",
    summary: `Restock report ${report.report_number} — ${items.length} product(s)`,
  });

  // Re-fetch with joined items so the client can render the PDF immediately
  const { data: fullReport } = await supabase
    .from("restock_reports")
    .select(
      `id, report_number, notes, created_by, created_at,
       restock_report_items(
         id, product_id, qty_before, qty_after, sort_order,
         product:products(id, sku, name_en, name_ar, unit_price)
       )`
    )
    .eq("id", report.id)
    .single();

  return NextResponse.json(fullReport ?? report, { status: 201 });
}
